version: '3'
networks:
   python_chat:
     external: true
services:
  bot:
    build: ./bot
    ports:
      - "9000:8000"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - python_chat
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
    - python_chat

  db:
    image: postgres
#    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: chat_server
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat_server
